### PR TITLE
test for xiao1819

### PR DESCRIPTION
**Pull request by xiao1819**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by kimisikainai** [comment]
这是啥?

**Comment by xiao1819** [comment]
这是我用来测试 pull request的

**Comment by kimisikainai** [comment]
好的,那我就不提交了,你已经有结论了.

**Comment by xiao1819** [comment]
好的 收到.

**Comment by xiao1819** [comment]
真实 merge下把,请 reopen.

**Pull request merged**
